version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: score_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - score_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: score_app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${PORT}:3000"
    networks:
      - score_net

networks:
  score_net:
    driver: bridge
